CREATE DATABASE ELETRONICA;

USE ELETRONICA;


CREATE TABLE PESSOAL (
    IDPESSOAL INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (20) NOT NULL,
    SOBRENOME VARCHAR (30) NOT NULL,
    SEXO ENUM('M','F') NOT NULL,
    CPF VARCHAR(15) UNIQUE,
    EMAIL VARCHAR(50) UNIQUE,
    ID_USUARIO INT UNIQUE
);

CREATE TABLE USUARIO (
    IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO VARCHAR(30)
);

CREATE TABLE SENHA( 
    IDSENHA INT PRIMARY KEY AUTO_INCREMENT,
    SENHA VARCHAR(30)
);

CREATE TABLE USUARIO_SENHA(
    ID_USUARIO INT,
    ID_SENHA INT,
    PRIMARY KEY(ID_USUARIO, ID_SENHA)
);

CREATE TABLE ENDERECO (
    IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    BAIRRO VARCHAR (30) NOT NULL,
    UF INT (2) NOT NULL,
    CEP VARCHAR (20) NOT NULL,
    NUMERO INT (8) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    RUA VARCHAR (50) NOT NULL,
    ID_PESSOAL INT UNIQUE
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    DDD INT(3) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_PESSOAL INT

);

--------------------------------Forum--------------------------------------
CREATE TABLE POST( 
    IDPOST INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR (30) NOT NULL,
    CONTEUDO VARCHAR(500) NOT NULL,
    ID_USUARIO INT

);

CREATE TABLE RESPOSTA(
    IDRESPOSTA INT PRIMARY KEY AUTO_INCREMENT,
    RESP VARCHAR (500),
    ID_POST INT

);

CREATE TABLE RESPOSTA_USUARIO(
    ID_RESPOSTA INT,
    ID_USUARIO INT,
    PRIMARY KEY (ID_RESPOSTA, ID_USUARIO)
);

CREATE TABLE TIPO(
    IDTIPO INT PRIMARY KEY AUTO_INCREMENT,
    TEMA ENUM('Dica','Duvida','Reclamação','Novidades') NOT NULL,
    ID_POST INT
);


--------------------------Compra e Venda---------------------

CREATE TABLE PECA(
    IDPECA INT PRIMARY KEY AUTO_INCREMENT,
    PECA VARCHAR(50) NOT NULL,
    PRECO FLOAT(100,2) NOT NULL,
    ID_USUARIO INT 

);


CREATE TABLE PECA_USUARIO(
    ID_PECA INT,
    ID_USUARIO INT
);

CREATE TABLE MARCA(
    IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
    MARCA VARCHAR(50) NOT NULL,
    ID_PECA INT

);


CREATE TABLE QUANTIDADE(
    IDQUANTIDADE INT PRIMARY KEY AUTO_INCREMENT,
    QUANTIDADE INT(100) NOT NULL,
    ID_PECA INT

);

CREATE TABLE ACAO(
    IDACAO INT PRIMARY KEY AUTO_INCREMENT,
    CxV ENUM('Compra','Venda') NOT NULL,
    ID_PECA INT

);


-- CONTRAINTS --

------------Login-------------

ALTER TABLE TELEFONE 
ADD CONSTRAINT FK_TELEFONE_PESSOAL 
FOREIGN KEY(ID_PESSOAL)
REFERENCES PESSOAL(IDPESSOAL);

ALTER TABLE PESSOAL
ADD CONSTRAINT FK_PESSOAL_USUARIO 
FOREIGN KEY(ID_USUARIO)
REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_PESSOAL 
FOREIGN KEY (ID_PESSOAL)
REFERENCES PESSOAL(IDPESSOAL);

ALTER TABLE USUARIO_SENHA
ADD CONSTRAINT FK_USUARIO
FOREIGN KEY(ID_USUARIO)
REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE USUARIO_SENHA
ADD CONSTRAINT FK_SENHA
FOREIGN KEY(ID_SENHA)
REFERENCES SENHA(IDSENHA);

------------------Forum-------------------
ALTER TABLE POST 
ADD CONSTRAINT FK_POST_USUARIO
FOREIGN KEY(ID_USUARIO)
REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE RESPOSTA
ADD CONSTRAINT FK_RESPOSTA_POST
FOREIGN KEY(ID_POST)
REFERENCES POST(IDPOST);

ALTER TABLE TIPO 
ADD CONSTRAINT FK_TIPO_POST
FOREIGN KEY(ID_POST)
REFERENCES POST(IDPOST);

ALTER TABLE RESPOSTA_USUARIO
ADD CONSTRAINT FK_RESPOSTA
FOREIGN KEY(ID_RESPOSTA)
REFERENCES RESPOSTA(IDRESPOSTA);

ALTER TABLE RESPOSTA_USUARIO
ADD CONSTRAINT FK_USUARIO
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(IDUSUARIO);

-----------------Compra e Venda---------------------

ALTER TABLE MARCA
ADD CONSTRAINT FK_MARCA_PECA
FOREIGN KEY (ID_PECA)
REFERENCES PECA(IDPECA);

ALTER TABLE ACAO
ADD CONSTRAINT FK_ACAO_PECA
FOREIGN KEY (ID_PECA)
REFERENCES PECA(IDPECA);

ALTER TABLE QUANTIDADE 
ADD CONSTRAINT FK_QUANTIDADE_PECA
FOREIGN KEY (ID_PECA)
REFERENCES PECA(IDPECA);

ALTER TABLE PECA_USUARIO
ADD CONSTRAINT FK_PECA
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE PECA_USUARIO
ADD CONSTRAINT FK_USUARIOPECA
FOREIGN KEY (ID_PECA)
REFERENCES PECA(IDPECA);
